---
#- name: add apt key
#  apt_key: id=02A818DD keyserver=keyserver.ubuntu.com state=present

#- name: add apt repository
#  apt_repository: repo='deb http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh trusty-cdh5 contrib' state=present

- name: install zookeeper package
  apt: name="{{ item }}" install_recommends=no force=yes state=present
  with_items:
    - zookeeper
    - zookeeperd

- name: generate zookeeper id
  template: src=myid.j2 dest=/var/lib/zookeeper/myid owner=root group=root mode=0644
  notify:
    - restart zookeeper

- name: generate zookeeper config
  template: src=conf/zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg owner=root group=root mode=0644
  notify:
    - restart zookeeper

- name: remove zookeeper sysvinit
  file: path=/etc/init.d/zookeeper state=absent
  notify:
    - restart zookeeper

- name: register zookeeper service
  service: name=zookeeper state=started

- name: register zookeeper service with the consul agent
  consul: service_name=zookeeper service_port={{ zookeeper_client_port }} script="/usr/share/zookeeper/bin/zkServer.sh status" interval=60s timeout=2s