---
- name: add apt key
  apt_key: id=D88E42B4 keyserver=keyserver.ubuntu.com state=present

- name: add apt repository
  apt_repository: repo='deb http://packages.elastic.co/logstash/2.0/debian stable main' state=present

- name: install logstash package
  apt: name="{{ item }}" install_recommends=no state=present
  with_items:
    - logstash

- name: generate logstash config
  template: src=conf/logstash.conf.j2 dest=/etc/logstash/conf.d/logstash.conf owner=root group=root mode=0644
  notify:
    - restart logstash

- name: configure logstash packages
  template: src=default/logstash.j2 dest=/etc/default/logstash owner=root group=root mode=0644
  notify:
    - restart logstash

#- name: configure logstash upstart
#  template: src=init/logstash.conf.j2 dest=/etc/init/logstash.conf owner=root group=root mode=0644
#  notify:
#    - restart logstash

- name: register logstash service
  service: name=logstash state=started