---
- name: add apt key
  apt_key: id=2C52609D keyserver=keyserver.ubuntu.com state=present

- name: add apt repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

- name: install kernel extras
  apt: name="{{ item }}" install_recommends=no state=present
  with_items:
    - linux-image-extra-{{ ansible_kernel }}

- name: install package
  apt: name="{{ item }}" install_recommends=no state=present
  with_items:
    - docker-engine

- name: configure grub
  lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=""' line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
  notify: 
    - update grub

- name: configure docker files
  file: path=/etc/init.d/docker state=absent

- name: configure docker packages
  template: src=default/docker.j2 dest=/etc/default/docker owner=root group=root mode=0644
  notify:
    - restart docker

- name: configure docker upstart
  template: src=init/docker.conf.j2 dest=/etc/init/docker.conf owner=root group=root mode=0644
  notify:
    - restart docker

- name: register docker service
  service: name=docker state=started

- name: register docker service with the consul agent
  consul: service_name=docker service_port=2375 script="docker info" interval=60s timeout=2s