---
- name: install kubernetes script
  copy: src="make-kube-cert.sh" dest="{{ kube_script_dir }}" owner=root group=root mode=0744
  
- name: generate kubernetes certs
  command: "{{ kube_script_dir }}/make-kube-cert.sh {{ inventory_hostname }}"
  args:
    creates: "{{ kube_certs_dir }}/server.crt"
  environment:
    MASTERS_IP:   "{% for host in groups[kube_masters_group] %}{{ hostvars[host].private_ipv4 }}{% if not loop.last %} {% endif %}{% endfor %}"
    MASTERS_NAME: "{% for host in groups[kube_masters_group] %}{{ hostvars[host].inventory_hostname }}{% if not loop.last %} {% endif %}{% endfor %}"
    CERT_DIR:     "{{ kube_certs_dir }}"
    DNS_DOMAIN:   "{{ kube_dns_domain }}"
    SERVICE_CLUSTER_IP_RANGE: "{{ kube_service_addresses }}"


