---
- name: install kubernetes script
  copy: src="make-kube-token.sh" dest="{{ kube_script_dir }}" owner=root group=root mode=0744
 
- name: generate kubernetes tokens for master components
  command: "{{ kube_script_dir }}/make-kube-token.sh {{ item[0] }}-{{ item[1] }}"
  environment:
    TOKEN_DIR: "{{ kube_tokens_dir }}"
  with_nested:
    - [ "system:controller_manager", "system:scheduler", "system:kubectl", 'system:proxy' ]
    - "{{ groups[kube_masters_group] }}"
  register: kube_tokens
  changed_when: "'Added' in kube_tokens.stdout"
  notify:
    - restart kubelet

- name: generate kubernetes tokens for master components
  command: "{{ kube_script_dir }}/make-kube-token.sh {{ item[0] }}-{{ item[1] }}"
  environment:
    TOKEN_DIR: "{{ kube_tokens_dir }}"
  with_nested:
    - [ "system:kubelet", "system:proxy" ]
    - "{{ groups[kube_minions_group] }}"
  register: kube_tokens
  changed_when: "'Added' in kube_tokens.stdout"
  notify:
    - restart kubelet
