---
- name: prepare prometheus directory
  file: path="{{ item }}" state=directory owner=root group=root mode=0644
  with_items:
    - "{{ prometheus_config_dir }}"

- name: generate prometheus config
  template: src=conf/prometheus.yml.j2 dest={{ prometheus_config_dir }}/prometheus.yml  owner=root group=root mode=0644











