---
etcd_group: "clusters"

etcd_discovery: ~
etcd_discovery_srv: ~

etcd_interface: eth1
etcd_client_interface: "{{ etcd_interface }}"
etcd_peer_interface: "{{ etcd_interface }}"
etcd_client_port: 2379
etcd_peer_port: 2380
etcd_client_scheme: http
etcd_peer_scheme: http

etcd_initial_cluster_state: new
etcd_initial_cluster_token: etcd-cluster

etcd_initial_advertise_peer_urls: "{{ etcd_peer_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + etcd_peer_interface]['ipv4']['address'] }}:{{ etcd_peer_port }}"
etcd_advertise_client_urls: "{{ etcd_client_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + etcd_client_interface]['ipv4']['address'] }}:{{ etcd_client_port }}"
etcd_listen_client_urls: "{{ etcd_client_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + etcd_client_interface]['ipv4']['address'] }}:{{ etcd_client_port }},{{ etcd_client_scheme }}://127.0.0.1:{{ etcd_client_port }}"
etcd_listen_peer_urls:  "{{ etcd_peer_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + etcd_peer_interface]['ipv4']['address'] }}:{{ etcd_peer_port }}"