---
etcd_servers_group: role=control

etcd_peer_port: 2380
etcd_client_port: 2379
etcd_peer_scheme: http
etcd_client_scheme: http

etcd_initial_cluster_state: new
etcd_initial_cluster_token: etcd-k8-cluster
etcd_initial_cluster: "{% for host in groups[etcd_servers_group] %}{{ hostvars[host].inventory_hostname }}={{ etcd_peer_scheme }}://{{ hostvars[host].private_ipv4 }}:{{ etcd_peer_port }}{% if not loop.last %},{% endif %}{% endfor %}"
