---
influxdb_servers_group: role=control


# If multiple servers are specified, whether to create a clustered configuration
# NOTE:
#   - Do not attempt to cluster previously-unclustered servers. This can lead to data loss.
#   - This will overwrite your /etc/default/influxdb file (though it makes a backup)
influxdb_cluster_servers: no
# When clustering is enabled, whether or not to overwrite the /etc/hosts file with raw
# IPs (may be useful if no DNS resolution).
influxdb_overwrite_hosts_file: yes


# InfluxDB configuration file options
influxdb_disable_reporting: false

## Meta Settings
influxdb_meta_enabled: true
influxdb_meta_dir: /var/lib/influxdb/meta
influxdb_meta_hostname: localhost
influxdb_meta_port: 8088
influxdb_meta_retention_autocreate: "true"
influxdb_meta_election_timeout: 1s
influxdb_meta_heartbeat_timeout: 1s
influxdb_meta_leader_lease_timeout: 500ms
influxdb_meta_commit_timeout: 50ms
influxdb_meta_cluster_tracing: "false"
