---
- name: install system package
  apt: name="{{item}}" install_recommends=no state=present
  with_items:
    - ntp
    - ntpdate
    - python-pip

- name: install pip
  pip: name=pip state=latest

- name: install python library
  pip: name="{{item}}" state=present
  with_items:
    - python-consul

- name: install system utilities
  copy: src="{{item}}" dest="/usr/bin/" owner=root group=root mode=0755
  with_items:
    - nsenter

#- name: install docker library
#  pip: name=docker-py version=1.1.0 state=present

- name: configure system hosts
  template: src=hosts.j2 dest=/etc/hosts mode=0644

- name: configure system authorizedkey
  authorized_key: user=root key="{{ lookup('file', '/Users/qsma/.ssh/id_rsa.pub') }}"