---
- name: Kube-DNS | generate kube-dns pod manifests
  template: src="conf/addons/kube-dns-rc.yml" dest="/etc/kubernetes/manifests/kube-dns-rc.yml" owner=root group=root mode=0644
  register: kube_dns_rc_def

- name: Kube-DNS | generate kube-dns pod manifests
  template: src="conf/addons/kube-dns-svc.yml" dest="/etc/kubernetes/manifests/kube-dns-svc.yml" owner=root group=root mode=0644
  register: kube_dns_svc_def

- name: Kube-DNS | create or update replication controller
  kube: filename="/etc/kubernetes/manifests/kube-dns-rc.yml" state="{{ kube_dns_rc_def.changed | ternary('latest','present') }}"
  when: kube_addons_dns
  delegate_to: "{{ groups[kube_masters_group][0] }}"
  ignore_errors: yes
  run_once: true

- name: Kube-DNS | create or update replication controller
  kube: filename="/etc/kubernetes/manifests/kube-dns-svc.yml" state="{{ kube_dns_svc_def.changed | ternary('latest','present') }}"
  when: kube_addons_dns
  delegate_to: "{{ groups[kube_masters_group][0] }}"
  ignore_errors: yes
  run_once: true