---
- name: create kube-system namespace
  kube: filename="/etc/kubernetes/manifests/kube-system.yml"
  delegate_to: "{{ groups[kube_masters_group][0] }}"
  ignore_errors: yes
  run_once: true

- include: kube-ui.yml
  when: kube_addons_ui == true

- include: kube-dns.yml
  when: kube_addons_dns == true

- include: kube-heapster.yml
  when: kube_addons_heapster == true

- include: kube-grafana.yml
  when: kube_addons_grafana == true