---
- name: create kube-system namespace
  kube: filename="/etc/kubernetes/manifests/kube-system.yml" resource=namespace state=present
  delegate_to: "{{ groups[kube_masters_group][0] }}"
  ignore_errors: yes
  run_once: true

- include: kube-ui.yml
  when: kube_addons_ui == true

- include: kube-dns.yml
  when: kube_addons_dns == true

#- include: kube-logging.yml
#  when: kube_addons_logging == true

- include: kube-monitoring.yml
  when: kube_addons_monitoring == true