---
- name: install etcd scheduler
  marathon:
    state: present
    name: "/etcd"
    host: "http://127.0.0.1:9080"
    cpus: 0.2
    memory: 128.0
    ports:
      - 1
      - 2
      - 3
    instances: 1
    container:
      type: "DOCKER"
      docker:
        image: "mesosphere/etcd-mesos"
        network: "HOST"
    env:
      FRAMEWORK_NAME: "etcd"
      WEBURI: "http://$HOST:$PORT0/stats"
      ZK_PERSIST: "zk://zookeeper.service.serv.local:2181/etcd"
      MESOS_MASTER: "zk://zookeeper.service.serv.local:2181/mesos"
      AUTO_RESEED: "true"
      CLUSTER_SIZE: 3
  delegate_to: "{{ groups[etcd_servers_group][0] }}"
  ignore_errors: yes
  run_once: true