apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v10
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v10
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v10
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube-dns
        image: gcr.io/google_containers/kube2sky:1.12
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        args:
        - -etcd-server=http://etcd.service.{{ serv_dns_domain }}:{{ etcd_client_port }}
        - -domain={{ kube_dns_domain }}
        - -v=1
      - name: kube-healthz
        image: gcr.io/google_containers/exechealthz:1.0
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.default.svc.{{ kube_dns_domain }} localhost >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP