apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-grafana
  namespace: kube-system
  labels: 
    k8s-app: kube-grafana
    version: v2
    kubernetes.io/cluster-service: "true"
spec: 
  replicas: 1
  selector: 
    k8s-app: kube-grafana
    version: v2
  template: 
    metadata: 
      labels: 
        k8s-app: kube-grafana
        version: v2
        kubernetes.io/cluster-service: "true"
    spec: 
      containers: 
        - name: kube-grafana
          image: gcr.io/google_containers/heapster_grafana:v2.6.0
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 3000
          env:
            - name: INFLUXDB_SERVICE_URL
              value: http://influxdb.service.{{ serv_dns_domain }}:8086
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_SERVER_ROOT_URL
              value: /api/v1/proxy/namespaces/kube-system/services/kube-grafana/
          volumeMounts:
          - name: grafana-persistent-storage
            mountPath: /var  
      volumes:
      - name: grafana-persistent-storage
        emptyDir: {}