apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-heapster
  namespace: kube-system
  labels:
    k8s-app: kube-heapster
    version: v11
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-heapster
    version: v11
  template:
    metadata:
      labels:
        k8s-app: kube-heapster
        version: v11
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube-heapster
        image: gcr.io/google_containers/heapster:v0.19.0
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 8082
        command:
        - /heapster
        - --listen_ip=0.0.0.0
        - --port=8082
        - --source=kubernetes:''
        - --sink=influxdb:http://influxdb.service.{{ serv_dns_domain }}:8086
        - --stats_resolution=30s
        - --sink_frequency=1m
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: etc-kubernetes
          readOnly: true
      volumes:
      - hostPath:
          path: /etc/kubernetes/
        name: etc-kubernetes