apiVersion: v1
kind: Service
metadata:
  name: kube-grafana
  namespace: kube-system
  labels: 
    k8s-app: kube-grafana
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeGrafana"
spec:
  selector: 
    k8s-app: kube-grafana
  ports: 
  - port: 80
    targetPort: 3000