apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-kibana
  namespace: kube-system
  labels:
    k8s-app: kube-kibana
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-kibana
    version: v1
  template:
    metadata:
      labels:
        k8s-app: kube-kibana
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube-kibana
        image: gcr.io/google_containers/kibana:1.3
        resources:
          limits:
            cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging.kube-system.svc.{{ kube_dns_domain }}:9200"
        ports:
        - containerPort: 5601
          protocol: TCP