---
zookeeper_servers_group: role=control


zookeeper_ensemble: dc1

# The zookeeper id
zookeeper_id: "
  {%- if zk_id is defined -%}
    {{ zk_id }}
  {%- else -%}
    {%- for host in groups[zookeeper_servers_group]|sort -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}
  {%- endif -%}
"
# The number of milliseconds of each tick
zookeeper_tick_time: 2000
# The number of ticks that the initial synchronization phase can take
zookeeper_init_limit: 10
# The number of ticks that can pass between sending a request and getting an acknowledgement
zookeeper_sync_limit: 5
# the port at which the clients will connect
zookeeper_client_port: 2181
# the ports used for leader election
zookeeper_server_ports: 2888:3888
