apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: mesosphere/kubernetes-mesos
    command:
    - km
    - controller-manager
    - --master=http://127.0.0.1:8080
    - --cloud-provider=mesos
    - --cloud-config={{ kube_config_dir }}/cloud.cfg
    - --cluster-name=kubernetes
    - --root-ca-file={{ kube_certs_dir }}/ca.crt
    - --service-account-private-key-file={{ kube_certs_dir }}/server.key
    - --v=1
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: etc-kubernetes
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/
    name: etc-kubernetes
