apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: mesosphere/kubernetes-mesos
    command:
    - km
    - scheduler
    - --address=0.0.0.0
    - --port=10251
    - --advertised-address={{ private_ipv4 }}:10251
    - --api-servers={% for host in groups[kube_masters_group] %}{{ hostvars[host].private_ipv4 }}:8080{% if not loop.last %},{% endif %}{% endfor %}

    - --etcd-servers={% for host in groups[etcd_servers_group] %}{{ etcd_client_scheme }}://{{ hostvars[host].private_ipv4 }}:{{ etcd_client_port }}{% if not loop.last %},{% endif %}{%-endfor %}

    - --framework-name=kubernetes
    - --ha=true
    - --mesos-master={{ kube_mesos_master }}
    - --mesos-user=root
    - --cluster-dns={{ private_ipv4 }}
    - --cluster-domain={{ kube_dns_domain }}
     - --v=2
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1